# "Unit 3 Sections 14 and 15"
> "Libraries and Random Values"
 
- toc: true
- branch: master
- badges: true
- comments: true
- permalink: /jupyter/libraries
- categories: [jupyter,markdown]

<style>
    .coolCode {
        color: #FFFFFF;
        font-family: monospace;
        border: 1px solid #404040;
        border-radius: 3px;
        background-color: #212121;
        padding: 1px 5px;
        font-size: 20px
    }
</style>

### wget https://raw.githubusercontent.com/aidenhuynh/CS_Swag/master/_notebooks/2022-11-30-randomvalues.ipynb

# Libraries

* A library is a collection of precompiled codes that can be used later on in a program for some specific well-defined operations. 
* These precompiled codes can be referred to as modules. Each module contains bundles of code that can be used repeatedly in different programs.
* A library may also contain documentation, configuration data, message templates, classes, and values, etc.

### Why are libraries important?
* Using Libraries makes Python Programming simpler and convenient for the programmer. 
* One example would be through looping and iteration, as we don’t need to write the same code again and again for different programs. 
* Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.

### A few libraries that simplify coding processes:
* **Pillow** allows you to work with images.
* **Tensor Flow** helps with data automation and monitors performance.
* **Matplotlib** allows you to make 2D graphs and plots.

The AP Exam Refrence Sheet itself is a library!
![Screenshot 2022-12-11 221853](https://user-images.githubusercontent.com/51098969/206974627-af98327c-d95d-4459-be67-cbaa3faaaa98.jpg)

## Hacks:
Research two other Python Libraries NOT DISCUSSED DURING LESSON and make a markdown post, explaining their function and how it helps programmers code.

### API’s
* An Application Program Interface, or API, contains specific direction for how the procedures in a library behave and can be used. 
* An API acts as a gateway for the imported procedures from a library to interact with the rest of your code.

### Activity: Walkthrough with NumPy
* Install NumPy on VSCode:
    1. Open New Terminal In VSCode:
    2. pip3 install --upgrade pip
    3. pip install numpy 
 
REMEMBER: When running library code cells use Python Interpreter Conda (Version 3.9.12)
 
### Example of using NumPy for arrays:

In [3]:
import numpy as np
new_matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
 
print (new_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Example of using NumPy for derivatives:

In [65]:
import numpy as np
 
# defining polynomial function
var = np.poly1d([2, 0, 1])
print("Polynomial function, f(x):\n", var)
 
# calculating the derivative
derivative = var.deriv()
print("Derivative, f(x)'=", derivative)
 
# calculates the derivative of after
# given value of x
print("When x=5  f(x)'=", derivative(5))

Polynomial function, f(x):
    2
2 x + 1
Derivative, f(x)'=  
4 x
When x=5  f(x)'= 20


## Random Values

* Random number generation (RNG) produces a random number (crazy right?)
    - This means that a procedure with RNG can return different values even if the parameters (inputs) do not change
* CollegeBoard uses <code class="coolCode">RANDOM(A, B)</code>, to return an integer between integers <code class="coolCode">A</code> and <code class="coolCode">B</code>.
    - RANDOM(1, 10) can output 1, 2, 3, 4, 5, 6, 7, 8, 9, or 10
    - In Python, this would be <code class="coolCode">random.randint(A, B)</code>, after importing Python's "random" library (<code class="coolCode">import random</code>)
    - JavaScript's works a little differently, with <code class="coolCode">Math.random()</code> returning a value between 0 and 1.
        - To match Python and CollegeBoard, you could make a procedure like [this](https://stackoverflow.com/a/7228322)

#### CollegeBoard Example: What is the possible range of values for *answ3*
![CollegeBoard](https://i.ibb.co/Wt90Hbz/Screen-Shot-2022-12-12-at-7-27-58-AM.png)


#### Convert the following procedure to Python, then determine the range of outputs if n = 5.
<pre>
<font color=white>
PROCEDURE Dice(n)
	sum ← 0
	REPEAT UNTIL n = 0
		sum ← sum + RANDOM(1, 6)
		n ← n - 1
	RETURN sum
</font>
</pre>


In [361]:
import random # Fill in the blank

def Dice(n):
    sum = 0
    while n > 0:
        sum = sum + random.randint(1, 6)
        n = n - 1 
    return sum
    
Dice(5) # Will output a range of 5 to 30

19

## Homework
1. Write a procedure that generates *n* random numbers, then sorts those numbers into lists of even and odd numbers (JS or Python, Python will be easier).

2. Using NumPy and only coding in python cell, find the answer to the following questions:
    a. What is the derivative of 2x^5 - 6x^2 + 24x?
    b. What is the derivative of (13x^4 + 4x^2) / 2 when x = 9? 

3. Suppose you have a group of 10 dogs and 10 cats, and you want to create a random order for them. Show how random number generation could be used to create this random order.

# Homework 1
- Write a procedure that generates *n* random numbers, then sorts those numbers into lists of even and odd numbers (JS or Python, Python will be easier)

In [40]:
import random

def numsorter(n = int): # for n integers
    numbers = [random.randint(0, 1000) for i in range(n)] # assigns each number in range with an index value and number
    even = [num for num in numbers if num % 2 == 0] # If remainder is = 0, then a number is even so module helps
    odd = [num for num in numbers if num % 2 > 0] # If remainder is greater than 0, then its an odd number so we use module

    print("Odd Numbers:\n", odd)
    print("\nEven Numbers:\n", even)

n = int(input("Enter any number (1-1000)"))
numsorter(n) # runs procedure 
print("\nInput:\n", n)

Odd Numbers:
 [249, 947, 843, 413, 881, 367, 669, 415, 713, 731, 591, 391, 135, 857, 977, 37, 229, 369, 889, 801, 335, 123, 773, 983, 393, 267, 155, 307, 569, 559, 599, 481, 639, 527, 515, 803, 631, 793, 885, 273, 1, 403, 731, 517, 277, 617, 203, 799, 149, 29, 759, 877, 585, 203, 501, 561, 103, 129, 405, 875, 217, 863, 545, 889, 25, 249, 471, 665, 429, 977, 797, 787, 115, 827, 181, 729, 45, 139, 37, 47, 679, 247, 619, 41, 485, 491, 217, 741, 619, 881, 187, 377, 501, 787, 131, 763, 117, 429, 173, 879, 689, 663, 677, 637, 245, 949, 487, 257, 867, 297, 911, 869, 863, 47, 675, 303, 387, 941, 727, 69, 217, 783, 335, 217, 989, 451, 783, 449, 783, 865, 771, 389, 277, 647, 641, 235, 225, 179, 213, 437, 875, 489, 331, 71, 965, 741, 955, 807, 1, 587, 887, 413, 283, 77, 727, 155, 49, 963, 11, 811, 195, 591, 83, 831, 97, 411, 667, 385, 465, 165, 211, 667, 847, 909, 861, 655, 679, 29, 385, 825, 529, 657, 661, 79, 995, 961, 181, 745, 967, 83, 909, 217, 21, 795, 57, 893, 913, 349, 395, 699, 369, 553,

# Homework 2
- Using NumPy and only coding in python cell, find the answer to the following questions:
    - a. What is the derivative of 2x^5 - 6x^2 + 24x?
    - b. What is the derivative of (13x^4 + 4x^2) / 2 when x = 9? 

In [90]:
import numpy as np
 
print("What is the derivative of 2x^5 - 6x^2 + 24x?\n")

var = np.poly1d([2, 0, 0, -6, 24, 0]) # works like x^5, x^4, x^3, x^2, x, 1
print("Polynomial function, f(x):\n", var)
 

derivative = np.polyder(var) # takes the derivative of a polynomial with higher powers
print("Derivative, f(x)'=\n", derivative)

print("\n\nWhat is the derivative of (13x^4 + 4x^2) / 2 when x = 9?\n")

var = np.poly1d([13, 0, 4, 0, 0]) /2 # dividing by 2 off the bat
print("Polynomial function, f(x):\n", var)

derivative = np.polyder(var) # takes the derivative of a polynomial with higher powers
print("Derivative, f(x)'=\n", derivative)
print("Derivative, f(9)'=\n", derivative(9)) # replaces x's with 9 and solves polynomial


What is the derivative of 2x^5 - 6x^2 + 24x?

Polynomial function, f(x):
    5     2
2 x - 6 x + 24 x
Derivative, f(x)'=
     4
10 x - 12 x + 24


What is the derivative of (13x^4 + 4x^2) / 2 when x = 9?

Polynomial function, f(x):
      4     2
6.5 x + 2 x
Derivative, f(x)'=
     3
26 x + 4 x
Derivative, f(9)'=
 18990.0


# Homework 3
- Suppose you have a group of 10 dogs and 10 cats, and you want to create a random order for them. Show how random number generation could be used to create this random order.

In [98]:
import random 

Cats = ["Cat" + str(i) for i in range(10)] # creates Cat1 and so on by adding the integer from range to a index value
Dogs = ["Dog" + str(i) for i in range(10)] # creates Dog1 and so on by adding the integer from range to a index value

Pets = Cats + Dogs # adds the lists together creating one big list

random.shuffle(Pets) # shuffles the big list 

print(Pets)

['Cat9', 'Cat5', 'Dog2', 'Cat3', 'Cat2', 'Cat8', 'Dog5', 'Cat7', 'Dog7', 'Dog3', 'Dog4', 'Dog9', 'Cat4', 'Cat0', 'Dog8', 'Cat6', 'Dog0', 'Dog1', 'Cat1', 'Dog6']
